### POST auth
POST http://localhost:7070/auth
Content-Type: application/json

{"login": "vasya", "password": "password"}

### GET user
GET http://localhost:7070/private/me
Authorization: Bearer ccfa2202-af26-4cc7-8490-82c36cc15d7c
Accept: application/json

### GET news
GET http://localhost:7070/private/news
Authorization: Bearer ccfa2202-af26-4cc7-8490-82c36cc15d7c
Accept: application/json

###