### POST auth
POST http://localhost:7070/auth
Content-Type: application/json

{"login": "vasya", "password": "password"}

### GET user
GET http://localhost:7070/private/me
Authorization: Bearer bce42fd8-cc25-4798-a36b-62c09f33d581
Accept: application/json

### GET news
GET http://localhost:7070/private/news
Authorization: Bearer bce42fd8-cc25-4798-a36b-62c09f33d581
Accept: application/json

###